### PR TITLE
export public api / types used by installLogsPrinter / installLogsCollector

### PR DESCRIPTION
**Pull request by tebeco**
As `installLogsPrinter` and `installLogsCollector` are exported, then the inner types should also be exported:

`installLogsPrinter.d.ts`:
* `PluginOptions`
* `Severity`
`installLogsCollector.d.ts`:
* `SupportOptions`
* `Severity`

Funny note:
`Severity` is redundant and might be moved to a common place some day when the repo will be migrated to typescript, also the typpings would be emitted by `tsc` so they would not need any manual maintainance

### CODE REVIEW

**Comment by tebeco** [comment]
@archfz if you have any leads on how changing a `.d.ts` would break ~6 or more test or how to fix it, I'm all hear

**Comment by archfz** [comment]
Looks good. I will retry the job. It most likely is flakiness.

**Comment by archfz** [comment]
I have pushed some flakiness fixes for this test into develop.  Please rebase and retarget your PR against develop.

I would also prefer not to do a release only with this change. Could you maybe take a look into https://github.com/archfz/cypress-terminal-report/issues/127 as well? Would appreciate some fresh eyes.

**Comment by tebeco** [comment]
I wish github PR UI had a simple button to rebase.
Now i'm forced to clone my own repo 🙃 was doing that from the portal

**Comment by tebeco** [comment]
@archfz, that seems to have fixed it ;)

**Pull request merged**
