### PR TITLE
Update Usage in Readme

### PR DESCRIPTION
**Pull request by zentby**
#34

### CODE REVIEW

**Comment by archfz** [comment]
@zentby for some reason one of the commands order changed suddenly not quite sure why https://travis-ci.com/github/archfz/cypress-terminal-report/builds/171339539; can you change that ? after you've done it i will make a patch release for this so that the npm readme is updated as well

**Comment by zentby** [comment]
@archfz I'm not sure what do you mean by "order changed". The last line of the test doesn't make much sense to me...
```js
 cy.get('.breaking-get', {timeout: 1});
```

**Comment by archfz** [comment]
@zentby that command is for breaking the test as fast as possible but it has nothing to do why the tests fail here

If you look at the end of the travis CI output this line: `cy:command (K): wait	@putComment` from the expected spec file https://github.com/archfz/cypress-terminal-report/blob/master/test/output/out.spec.txt changed it's location. I am not sure why tough, you can move it no problem to fix the test.

**Comment by zentby** [comment]
@archfz I had a look at the file and test, I think the file is actually correct. Somehow the Travis run into a strange state.
image

Hence retry the CI

**Pull request merged**
