### PR TITLE
Improved parsing of cy.request

### LINKED ISSUE #58: Certain cy.request errors breaks the logging
There are two scenarios in which this plugin fails to parse the result of a cy.request command. This results in the rather limited log "e.onFail is not a function", which hides the actual cy.request error also in the cypress command log.

The scenarios are:
1) When cy.request is called with a `log: false` option and the request fails (non-success error code)
2) When cy.request fails due to a network error (timeout, connection reset ...)

I am working on a PR to mitigate these scenarios and use a cy.request parsing method that works in all scenarios.

### PR DESCRIPTION
**Pull request by bjowes**
Fix #58

### CODE REVIEW

**Comment by bjowes** [comment]
I see that it fails one of the tests, will look into it

**Comment by bjowes** [comment]
Seems the tests are sensitive to timing in the response from the API calls, all good when run a second time.

**Comment by archfz** [comment]
Real good stuff.

**Comment by archfz** [comment]
Released in 2.3.0

**Pull request merged**
